### ISSUE TITLE
Make it work on the whole note box like Excalidraw

### ISSUE THREAD

**Issue by navakelvin** [juliusgb/obsidian-tldraw-plugin#51]
Could you make this plugin show up in the whole note box and not just in a small box?

Maybe you could take a look at the Excalidraw plugin code for Obsidian and see how they did it.
https://github.com/zsviczian/obsidian-excalidraw-plugin

![image](https://user-images.githubusercontent.com/77164639/212798067-af2cc581-001a-4c96-bb4d-c53f5781dddb.png)

Thanks in advance!

**Comment by juliusgb** [comment]
Yep. That depends on getting the `Styles` pop-up to be displayed like it does on tldraw.com (https://github.com/juliusgb/obsidian-tldraw-plugin/issues/47)

That extra space on the right is a workaround for the `Styles` to pop-up -> https://github.com/juliusgb/obsidian-tldraw-plugin/issues/39
