### ISSUE TITLE
unable to load plugin from git clone

### ISSUE THREAD

**Issue by mikemccracken** [juliusgb/obsidian-tldraw-plugin#9]
Hi! thanks for working on this. I wanted to give it a try, but I wasn't able to load the plugin.
For context, I'm not super familiar with either JS or Obsidian development, and I am on a Mac.

I cloned this repo into `Obsidian Vault/.obsidian/plugins/obsidian-tldraw-plugin/` and restarted Obsidian, but I wasn't seeing anything new. I took a guess and added `"obsidian-tldraw-plugin"` to the list in `community-plugins.json`.
When I restarted after that, I saw a brief error and found this in the javascript console in the obsidian dev tools:

```
app.js:1 Obsidian Developer Console
plugin:dataview:20681 Dataview: version 0.5.43 (requires obsidian 0.13.11)
app.js:1 Plugin failure: obsidian-tldraw-plugin Error: ENOENT: no such file or directory, open '/Users/mikmccra/Documents/Obsidian Vault/.obsidian/plugins/obsidian-tldraw-plugin/main.js'
(anonymous) @ app.js:1
plugin:dataview:13951 Dataview: all 842 files have been indexed in 0.389s (842 cached, 0 skipped).
```

I'm guessing there's some compilation step to generate the final JS that I am missing?

**Comment by juliusgb** [comment]
Ahh yes, I forgot to add that, sorry. I'm also new to JS and TypeScript :)

In the terminal, go to `Obsidian Vault/.obsidian/plugins/obsidian-tldraw-plugin/` and run the following:
- `npm rund install `
- `npm run dev`

**Comment by juliusgb** [comment]
I've updated the documentation
- For users: https://github.com/juliusgb/obsidian-tldraw-plugin#setup
- For developing: https://github.com/juliusgb/obsidian-tldraw-plugin/blob/main/guides/development.md

**Comment by mikemccracken** [comment]
Thanks, that worked. Do I actually need the 'npm run' ? I killed that and the plugin still seemed to work.

**Comment by juliusgb** [comment]
`npm run` is not required if you're following the "user guide": as long as the 3 files (`main.js`, `manifest.json`, `styles.css`) are in the folder, `/path/to/ObsidianVault/plugins/.obsidian/plugins/plugins/obsidian-tldraw-plugin`, the plugin should work.

`npm run dev` is for when you're changing the plugin's code.
